### ISSUE TITLE
[FEATURE] - Validate Emails and Created user

### ISSUE THREAD

**Issue by Chocrates** [froi/add_invite_user#9]
Validate that the email requested is part of a specified domain.  IE if you only want people with your company's email address to be able to be added.  
Additionally only accept issues when they are created by a single user, presumably a bot.

**Comment by Chocrates** [comment]
@froi @jasonmacgowan What shall we do if the requested user fails the email validation?  I am guessing throw an error and the notification action will be smart enough to action the specific error?

**Comment by froi** [comment]
I just took a look at the PR #17 and left some comments there. Thanks for all the hard work. I'm pretty sure that a totally misunderstood the use of what I called in the PR a "trusted user". Can you please shed some light on my confusion in the PR itself. 

Thanks again!!!

**Comment by froi** [comment]
> @froi @jasonmacgowan What shall we do if the requested user fails the email validation? I am guessing throw an error and the notification action will be smart enough to action the specific error?

I think we should set the actions' `message` and `stepStatus` output to reflect that it failed. That way whatever action consumes that can figure out what to do.
